# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: ["main"]
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: stage
          github_token: ${{ secrets.TOKEN }}
      # - name: Merge by labeled
      #   uses: tukasz/direct-merge-action@master
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #     source-branch: main
      #     target-branch: stage
