# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: stage
          github_token: ${{ secrets.TOKEN }}
      - name: Merge development -> development
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: development
          github_token: ${{ secrets.TOKEN }}
      # - name: Merge by labeled
      #   uses: tukasz/direct-merge-action@master
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #     source-branch: main
      #     target-branch: stage
